[package]
name = "neverest"
description = "CLI to synchronize PIM collections: mail, contact, calendar…"
version = "1.0.0-rc"
authors = ["Clément DOUIN (soywod) <clement.douin@posteo.net>"]
rust-version = "1.89"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "email"]
keywords = ["cli", "email", "contacts", "imap", "sync"]
homepage = "https://pimalaya.org"
repository = "https://github.com/pimalaya/neverest"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rustls-ring", "imap", "smtp", "msgraph"]
carddav = ["dep:io-webdav", "dep:io-http", "io-pim-discovery/rfc6764"]
imap = ["dep:io-imap", "io-imap/client", "io-imap/scram"]
smtp = ["dep:io-smtp", "io-smtp/client"]
msgraph = ["dep:io-msgraph", "io-msgraph/client"]
native-tls = ["pimalaya-stream/native-tls", "io-pim-discovery/native-tls", "io-webdav?/native-tls", "io-imap?/native-tls", "io-msgraph?/native-tls", "io-smtp?/native-tls"]
rustls-aws = ["pimalaya-stream/rustls-aws", "io-pim-discovery/rustls-aws", "io-webdav?/rustls-aws", "io-imap?/rustls-aws", "io-msgraph?/rustls-aws", "io-smtp?/rustls-aws"]
rustls-ring = ["pimalaya-stream/rustls-ring", "io-pim-discovery/rustls-ring", "io-webdav?/rustls-ring", "io-imap?/rustls-ring", "io-msgraph?/rustls-ring", "io-smtp?/rustls-ring"]
vendored = ["pimalaya-stream/vendored", "io-webdav?/vendored", "io-imap?/vendored", "io-msgraph?/vendored", "io-smtp?/vendored"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"] }

[dev-dependencies]
tempfile = "3"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
crossbeam-queue = "0.3"
crossterm = { version = "0.29", default-features = false, features = ["serde"] }
dirs = "6"
io-http = { version = "0.5", default-features = false, optional = true }
io-imap = { version = "0.6", default-features = false, optional = true }
io-msgraph = { version = "0.3", default-features = false, optional = true }
io-pim-discovery = { version = "0.7", default-features = false, features = ["pacc", "autoconfig", "rfc6186"] }
io-pimdir = { version = "0.3", default-features = false, features = ["client"] }
io-replica = { version = "0.4", default-features = false }
io-sasl = { version = "0.1", default-features = false, features = ["saslprep", "scram"] }
io-smtp = { version = "0.3", default-features = false, optional = true }
io-webdav = { version = "0.2", default-features = false, optional = true }
log = "0.4"
mail-parser = { version = "0.11", features = ["serde"] }
percent-encoding = "2"
pimalaya-cli = { version = "0.2", default-features = false, features = ["terminal", "prompt", "wizard", "spinner", "imap", "smtp"] }
pimalaya-config = { version = "0.1", default-features = false, features = ["toml", "secret"] }
pimalaya-stream = { version = "0.3", default-features = false }
rfc2047-decoder = "1"
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shellexpand = "3.1"
toml = "1.1"
url = { version = "2.2", features = ["serde"] }

[patch.crates-io]
io-pimdir.git = "https://github.com/pimalaya/io-pimdir"
io-replica.git = "https://github.com/pimalaya/io-replica"
